name: OORIGACHI CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  CI TEST:
    name: CI Pipeline
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['16.x']
     steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: [16.x]
          cache: 'npm'
        run: npm ci
        run: npm test

  
  AUTO_DEPLOY:
    name: CD Pipeline 
    needs: CI Pipeline
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
                cd ${{ secrets.TEST_DEPLOY }}
                sudo git pull origin dev
                npm install
                pm2 restart server.js
                
